Use apiserver host/port from InfraStatus in reconciling Kube API Server
openshift/hypershift pull request #1319
Opened 2022-04-27 16:43 UTC by csrwng

**What this PR does / why we need it**:
Currently the KubeAPIServerParams are constructed with the API Server
address from the HCP status. This modifies reconciliation to use the
InfraStatus to obtain the API Server address.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

2022-04-27 16:55 UTC, alvaroaleman commented
/retest

2022-04-27 19:31 UTC, sjenning commented
/test verify

2022-04-27 19:32 UTC, sjenning commented
/lgtm

2022-04-27 19:42 UTC, sjenning requested changes

2022-04-27 19:42 UTC, sjenning commented on control-plane-operator/controllers/hostedcontrolplane/hostedcontrolplane_controller.go
> -	r.Log.Info("Reconciling infrastructure services")
we still need this

2022-04-27 20:10 UTC, sjenning commented
/test images
/lgtm

2022-04-28 14:59 UTC, csrwng commented
/hold
until we fix CI

2022-04-28 16:11 UTC, csrwng commented
/hold cancel

2022-04-28 16:11 UTC, csrwng commented
/retest-required

2022-04-28 22:49 UTC, merged

2022-05-02 13:11 UTC, csrwng commented
/cherry-pick release-4.10