[wip] Add etcd and etcd metrics certs, add etcd metrics proxy
openshift/hypershift pull request #1858
Opened 2022-11-10 20:47 UTC by ibihim

**What this PR does / why we need it**:

What:
- Decouple etcd trust chain from root CA.
- Use etcd proxy for metrics.
- Add etcd metrics trust chain.
- Add distinct certificates for etcd proxy. 

Why:
- Create distinct trust zones.
- Use distinct certs for metrics scraping.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

2022-11-14 11:06 UTC, ibihim commented on control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go
> -func CombinedCAConfigMap(ns string) *corev1.ConfigMap {
`git diff` fails here. Isn't removed. Is moved down.

2022-11-14 11:07 UTC, ibihim commented on control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go
> -func UserCAConfigMap(ns string) *corev1.ConfigMap {
`git diff` fails here. Isn't removed. Is moved down.

2022-11-14 11:07 UTC, ibihim commented on control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go
> -func EtcdClientSecret(ns string) *corev1.Secret {
`git diff` fails here. Isn't removed. Is moved down.

2022-11-14 11:07 UTC, ibihim commented on control-plane-operator/controllers/hostedcontrolplane/manifests/pki.go
> -func EtcdServerSecret(ns string) *corev1.Secret {
`git diff` fails here. Isn't removed. Is moved down.

2022-11-15 08:59 UTC, stlaz commented
/test e2e-aws

2022-11-16 16:41 UTC, stlaz requested changes

2022-11-16 16:41 UTC, stlaz commented on control-plane-operator/controllers/hostedcontrolplane/etcd/reconcile.go
>  			},
this port should not be published

2022-12-02 14:30 UTC, ibihim commented
/retest-required

2022-12-12 14:43 UTC, csrwng commented
/lgtm
/approve

2022-12-12 17:37 UTC, merged