Add e2e test for hosted cluster behind a proxy
openshift/hypershift pull request #2077
Opened 2023-01-26 13:46 UTC by enxebre

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Ref https://issues.redhat.com/browse/HOSTEDCP-731
blocked by https://issues.redhat.com/browse/OCPBUGS-6651

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

2023-01-26 13:46 UTC, enxebre commented
/hold

2023-01-30 20:11 UTC, enxebre commented
Needs https://github.com/openshift/cluster-network-operator/pull/1694

2023-02-07 13:07 UTC, enxebre commented
/test e2e-aws

2023-02-08 06:05 UTC, enxebre commented
/test e2e-aws

2023-02-09 08:09 UTC, enxebre commented
/test e2e-aws

2023-02-10 10:42 UTC, enxebre commented
needs https://github.com/openshift/cluster-storage-operator/pull/336
/test e2e-aws

2023-02-11 07:45 UTC, enxebre commented
/test e2e-aws

2023-02-13 11:21 UTC, enxebre commented
/test e2e-aws

2023-02-13 16:58 UTC, enxebre commented
/hold cancel

2023-02-13 17:00 UTC, sjenning requested changes

2023-02-13 17:00 UTC, sjenning commented on test/e2e/create_cluster_test.go
> +	if len(zones) >= 3 {
We don't need this one more than one test.  CreateCluster has it covered.

2023-02-13 17:00 UTC, sjenning commented
/hold

2023-02-13 17:19 UTC, sjenning commented
/hold cancel
/lgtm

2023-02-13 19:39 UTC, merged

2023-02-20 09:05 UTC, enxebre commented
/cherry-pick release-4.12