Simple CLI tracking and cleanup of generated secrets in clusters namespace
openshift/hypershift pull request #209
Opened 2021-05-06 20:54 UTC by screeley44

This PR adds a label based on `hypershift-cli-` + `InfraID` for uniqueness on `cluster create` command

```
kind: Secret
metadata:
  creationTimestamp: "2021-05-06T17:33:19Z"
  labels:
    createdby: hypershift-cli-sc45-trf25
```

and deletes the secrets on `cluster destroy` command

```
INFO[0079] Deleted role policy                           policy=sc42-hfvlp-worker-policy role=sc42-hfvlp-worker-role
INFO[0079] Deleted role                                  role=sc42-hfvlp-worker-role
INFO[0079] Deleting Secrets                              namespace=clusters
INFO[0079] Successfully destroyed cluster and infrastructure  infraID=sc42-hfvlp name=sc42 namespace=clusters
```

2021-05-06 20:56 UTC, screeley44 commented
references #186

2021-05-06 20:57 UTC, screeley44 commented
@ironcladlou - maybe too simple?

2021-05-06 21:01 UTC, ironcladlou commented
What if we leverage the infra ID more directly and not impose a naming convention, so maybe a label like `hypershift.openshift.io/auto-created-for-infra=$infra_id` (or something) which is both namespaced and also makes it easier to do a label selector using only the infra ID?

2021-05-06 21:02 UTC, ironcladlou commented on cmd/cluster/create.go
> +			if object.GetObjectKind().GroupVersionKind().Kind == "Secret" {
I wonder if we even need to filter — why not apply it to everything the CLI creates?

2021-05-11 13:09 UTC, ironcladlou requested changes
Just need to introduce a shared constant and I think this is ready to go

2021-05-11 14:17 UTC, screeley44 commented on cmd/cluster/destroy.go
> +			log.Info("Secrets not found based on labels, skipping delete", "namespace", o.Namespace, "labels", "hypershift-cli-" + o.InfraID)
@ironcladlou better now?

2021-05-11 14:17 UTC, ironcladlou approved these changes

2021-05-11 14:18 UTC, ironcladlou commented
/approve
/test e2e-aws

2021-05-11 14:31 UTC, ironcladlou commented
@screeley44 not sure what's up with `make verify` based on the PR contents — is that command returning 0 for you locally?

2021-05-11 15:45 UTC, ironcladlou commented
/test e2e-aws

2021-05-11 18:25 UTC, ironcladlou commented
Awesome, thanks!

/lgtm

2021-05-11 18:26 UTC, merged