Filtering data recolection only for aws instances running
openshift/hypershift pull request #2153
Opened 2023-02-09 17:18 UTC by jparrill

This enables the data recollection only in Nodes which are up and running

Signed-off-by: Juan Manuel Parrilla Madrid <jparrill@redhat.com>

2023-02-09 17:23 UTC, sjenning requested changes

2023-02-09 17:23 UTC, sjenning commented on test/e2e/util/dump/journals.go
> +	instanceRunning := int64(16)
lets just use `state.name` equal to `running` vs the `state.code`

2023-02-09 17:24 UTC, csrwng commented on test/e2e/util/dump/journals.go
> +			if instance.State.Code == &instanceRunning {
you should compare values, not pointers

2023-02-09 22:56 UTC, jparrill commented
PTAL @sjenning

2023-02-15 03:41 UTC, csrwng commented
/lgtm
/approve

2023-02-15 05:50 UTC, merged