HOSTEDCP-568: Update Konnectiviy socks5 proxy for IBM exepction
openshift/hypershift pull request #2366
Opened 2023-03-31 18:07 UTC by bryan-cox

**What this PR does / why we need it**:
* Add "iam.cloud.ibm.com" and "iam.test.cloud.ibm.com" to the list of domains to not route through Konnectivity. 
* Consolidates #1741 and #1722.

**Which issue(s) this PR fixes**:
Fixes [HOSTEDCP-568](https://issues.redhat.com/browse/HOSTEDCP-568)

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.

2023-03-31 18:12 UTC, bryan-cox commented
I can squash the second commit if we want. I left it as it's own commit to make it easier to peer review.

2023-04-03 13:03 UTC, bryan-cox commented
/retest-required

2023-04-05 13:26 UTC, sjenning requested changes

2023-04-05 13:26 UTC, sjenning commented on konnectivity-socks5-proxy/main.go
> +		strings.HasSuffix(host, "iam.cloud.ibm.com") ||
seems like `iam.cloud.ibm.com` and `iam.test.cloud.ibm.com` are redundant since they both end in `cloud.ibm.com`

2023-04-05 15:06 UTC, sjenning commented
infra flake
```
Error: failed to create infra: cannot create nat gateway route in private route table: InvalidNatGatewayID.NotFound: The natGateway ID 'nat-00e3e38544af2bbdb' does not exist
```

/retest-required

2023-04-06 11:48 UTC, bryan-cox commented
Several tests failing due to these two errors:
```
failed to reconcile PKI: failed to remove service ca annotation and secret
failed to describe vpc endpoints
```
/test e2e-aws

2023-04-06 16:51 UTC, muraee commented
/lgtm

2023-04-06 17:13 UTC, bryan-cox commented
/test e2e-aws

2023-04-11 16:14 UTC, merged