W/A for KubeVirt provider with RHCOS 9.2
openshift/hypershift pull request #2373
Opened 2023-04-04 09:57 UTC by orenc1

Due to changes in RHCOS 9.2, the ignition config is not able to be fetched with the openstack provider. However, it works with kubevirt ignition provider. Adding a workaround that uses a modified RHCOS containerdisk that sets the kernel command line parameter of `ignition.platform.id=kubevirt` instead of `ignition.platform.id=openstack`

This is needed until https://github.com/coreos/fedora-coreos-tracker/issues/1126 is resolved and we'll have our kubevirt artifact shipped with RHCOS.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

2023-04-04 10:23 UTC, qinqon requested changes

2023-04-04 10:23 UTC, qinqon commented on test/e2e/create_cluster_test.go
> +	// Test W/A until https://github.com/coreos/fedora-coreos-tracker/issues/1126 is resolved
Can we also reference: 
- https://github.com/coreos/ignition/issues/1574

2023-04-04 11:33 UTC, orenc1 commented
/test kubevirt-e2e-kubevirt-aws-ovn

2023-04-04 15:39 UTC, orenc1 commented on test/e2e/util/util.go
> +		waitTimeout = 60 * time.Minute
looks like with RHCOS 9.2 the boot time is longer, 30 minutes are not enough for the VM to fully boot twice. extending to 60.

2023-04-04 16:47 UTC, qinqon commented
/test foo

2023-04-04 16:48 UTC, qinqon commented
/test kubevirt-e2e-kubevirt-aws-ovn

2023-04-16 08:35 UTC, orenc1 commented
closing in favor of #2399 , that blocks the metadata server by EgressFirewall rule.
/close

2023-04-16 08:36 UTC, closed without merging