[CNV-31919] Validate KubeVirt platform required versioning
openshift/hypershift pull request #2948
Opened 2023-08-24 16:22 UTC by davidvossel

This PR only impacts the hypershift-operator. We are doing some validation checks to ensure that we only allow creation of HCPs with supported guest, mgmt, and infra versions.

The minimum requirements are
* HCP payload >= v4.14.0
* KubeVirt >= v1.0.0 [CNV 4.14]
* Kubernetes >= v1.27.0 [OCP 4.14]

2023-08-28 21:48 UTC, davidvossel commented
/test e2e-kubevirt-aws-ovn

2023-08-29 14:38 UTC, davidvossel commented on hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
> +		// The CNV QE team is using the kubevirt platform in unconventional ways
reword this

2023-08-29 15:28 UTC, davidvossel commented
/test e2e-kubevirt-aws-ovn

2023-09-01 17:50 UTC, davidvossel commented
/test e2e-kubevirt-aws-ovn

2023-09-04 08:25 UTC, qinqon requested changes

2023-09-05 14:13 UTC, nunnatsa reviewed
Question:

Should we add similar logic to the CLI, to fail fast when creating a KV cluster?

2023-09-07 15:34 UTC, davidvossel commented on hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
> +	return utilerrors.NewAggregate(errs)
I'd like that as well, there's a reason i went with the k8s version though.

Both k8s and kubevirt have a version endpoint that is viewable by anyone. The way to get the OCP version is to use inspect the `oc get clusterversion` object, which is not viewable by default. I didn't want to add the dependency for the infra kubeconfig to be required to read the clusterversion object on the infra cluster, so i stuck with the K8s version.

The k8s version, in our case, does align with 4.14

2023-09-07 15:54 UTC, davidvossel commented on hypershift-operator/controllers/hostedcluster/hostedcluster_controller.go
> +	if exists && strings.ToLower(val) == "true" {
yep, fixed

2023-09-07 15:55 UTC, davidvossel commented
@qinqon updated, ptal

2023-09-08 12:34 UTC, davidvossel commented
/retest

2023-09-08 13:30 UTC, qinqon approved these changes
/lgtm

2023-09-08 16:22 UTC, davidvossel commented
/retest-required

there was an ipi failure

2023-09-12 20:30 UTC, davidvossel commented
/test e2e-kubevirt-aws-ovn

2023-09-13 13:46 UTC, davidvossel commented
/test e2e-kubevirt-aws-ovn

ipi failure

2023-09-13 13:48 UTC, qinqon commented
/lgtm

2023-09-14 13:04 UTC, davidvossel commented
/hold cancel

the test failures have all been ci infra related. this should pass

2023-09-14 13:04 UTC, davidvossel commented
/test e2e-kubevirt-aws-ovn

2023-09-14 19:01 UTC, davidvossel commented
/test e2e-kubevirt-aws-ovn

ci failed because the post condition's must gather failed... INFO[2023-09-14T16:35:36Z] Step e2e-kubevirt-aws-ovn-gather-must-gather failed after 37m45s.

2023-09-14 21:59 UTC, merged