Remove unused ability to override KonnectivityImage
openshift/hypershift pull request #3101
Opened 2023-10-16 16:34 UTC by enxebre

Initially we allow overrding defaultKonnectivityImage so we could pin an image while let product builders inject their own. Konnectiviy image comes from payload now.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [ ] Subject and description added to both, commit and PR.
- [ ] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

2023-10-16 16:36 UTC, enxebre commented on control-plane-operator/hostedclusterconfigoperator/controllers/resources/konnectivity/params.go
> -	if _, ok := hcp.Annotations[hyperv1.KonnectivityAgentImageAnnotation]; ok {
@relyt0925 @hasueki to validate you are fine dropping this

2023-10-16 16:36 UTC, enxebre commented
/hold
to confirm https://github.com/openshift/hypershift/pull/3101#discussion_r1360945400

2023-10-16 17:15 UTC, hasueki requested changes
/hold IBM Cloud is still using this annotation for 4.10 clusters

2023-10-24 11:45 UTC, enxebre commented on control-plane-operator/main.go
> -			"konnectivity-server":            konnectivityServerImage,
Seems konnectivity-agent is fetched in the guest cluster agent `NewKonnectivityParams`

2024-03-24 00:00 UTC, closed without merging