OCPBUGS-31263: Add missing PodSecurityViolation alert
openshift/hypershift pull request #3733
Opened 2024-03-12 19:37 UTC by Evan-Reilly

These changes add a missing PodSecurityViolation alert found in OpenShift 4.15 (see https://github.ibm.com/alchemy-containers/armada-update/issues/5524 and https://www.redhat.com/en/blog/pod-security-admission-in-openshift-4.11 for more details).

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

2024-03-12 20:37 UTC, rtheis requested changes
@Evan-Reilly please see https://github.com/openshift/hypershift/pull/1406 for what else is needed to go along with this.

2024-03-13 16:56 UTC, rtheis commented
/ok-to-test

2024-03-13 17:05 UTC, rtheis commented
/hold

2024-03-15 19:41 UTC, rtheis commented
/retest

2024-03-16 18:08 UTC, rtheis commented
/remove-hold

2024-03-17 12:54 UTC, rtheis requested changes

2024-03-17 12:54 UTC, rtheis commented on control-plane-operator/hostedclusterconfigoperator/controllers/resources/alerts/assets/podsecurity-violation.yaml
> +# Source: https://raw.githubusercontent.com/openshift/cluster-kube-apiserver-operator/release-4.15/bindata/assets/alerts/podsecurity-violation.yaml
This source link is wrong.  In needs to be https://raw.githubusercontent.com/openshift/cluster-kube-apiserver-operator/release-4.15/bindata/assets/alerts/podsecurity-violations.yaml

2024-03-18 21:29 UTC, rtheis commented
/retest

2024-03-18 21:32 UTC, rtheis approved these changes
/lgtm

2024-03-19 10:26 UTC, rtheis commented
/retest

2024-03-19 16:44 UTC, Evan-Reilly commented
/retest

2024-03-19 20:41 UTC, rtheis commented
/retest

2024-03-20 21:42 UTC, rtheis commented
/assign @csrwng

2024-03-21 13:49 UTC, bryan-cox commented
/retest 
For Konflux

2024-03-21 13:51 UTC, bryan-cox commented
This PR will also need a Jira ticket appended to the front of the title.

Would you also squash the commits please?

2024-03-21 14:04 UTC, sjenning commented
/approve

2024-03-22 09:06 UTC, rtheis commented
/retest

2024-03-22 09:35 UTC, rtheis commented
/retest

2024-03-22 10:04 UTC, bryan-cox commented
/override "Red Hat Konflux"

Konflux is working again. The original error will not clear away without a rebase.

2024-03-22 16:35 UTC, merged

2024-03-22 16:38 UTC, rtheis commented
/cherry-pick release-4.15