OCPBUGS-34699: Allow access to root-ca configmap in cluster-network-operator role
openshift/hypershift pull request #4122
Opened 2024-05-30 20:39 UTC by riendeau

**What this PR does / why we need it**:

Adds `root-ca` to the `resourceNames` in the `cluster-network-operator` role to provide the access required.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:

https://issues.redhat.com/browse/OCPBUGS-34699

2024-05-30 20:41 UTC, rtheis commented
/ok-to-test

2024-05-30 20:42 UTC, rtheis commented
/jira refresh

2024-05-30 20:45 UTC, hasueki commented
/jira refresh

2024-05-30 20:51 UTC, hasueki approved these changes
/lgtm

2024-05-30 22:04 UTC, rtheis requested changes
Please update unit tests for this change.

2024-05-30 22:12 UTC, rtheis approved these changes
/lgtm

2024-05-31 02:03 UTC, riendeau commented
/retest-required

2024-05-31 08:29 UTC, rtheis commented
/retest-required

2024-05-31 13:18 UTC, riendeau commented
/retest-required

2024-05-31 19:40 UTC, rtheis commented
/retest-required

2024-05-31 19:40 UTC, riendeau commented
/retest-required

2024-06-01 00:25 UTC, riendeau commented
/retest-required

2024-06-02 14:14 UTC, riendeau commented
/assign davidvossel

2024-06-04 13:49 UTC, csrwng commented
/approve

2024-06-04 15:31 UTC, csrwng approved these changes

2024-06-04 15:31 UTC, csrwng commented
/approve

2024-06-04 20:00 UTC, riendeau commented
/retest-required

2024-06-04 21:43 UTC, merged

2024-06-04 21:44 UTC, rtheis commented
/cherry-pick release-4.16