Enforce privileged PSA by default
openshift/hypershift pull request #4834
Opened 2024-10-01 14:53 UTC by Evan-Reilly

**What this PR does / why we need it**:
OpenShiftPodSecurityAdmission feature gate is not enabled by default in 4.17 any longer. Therefore, to ensure namespace security is not enforcing restricted by default any longer, this PR is required to properly enforce privileged PSA by default.

- https://github.com/openshift/api/blob/release-4.17/features/features.go
- https://github.com/openshift/api/pull/2018

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

2024-10-01 17:11 UTC, rtheis reviewed
@Evan-Reilly please take a look at the failures

2024-10-01 17:11 UTC, rtheis commented on control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/config.go
> +		if strings.HasPrefix(fg, "OpenShiftPodSecurityAdmission") {
@Evan-Reilly ptal at this failure report.

2024-10-01 18:41 UTC, rtheis approved these changes
/lgtm

2024-10-01 20:32 UTC, rtheis requested changes
/hold for changes based on https://ibm-argonauts.slack.com/archives/C01C8502FMM/p1727808157696799.

2024-10-03 10:13 UTC, rtheis commented
/remove-hold

2024-10-03 10:13 UTC, rtheis commented
@Evan-Reilly please fix the following test:

```
{Failed  === RUN   TestCreateClusterRequestServingIsolation/Main/EnsurePSANotPrivileged
    util.go:667: pod admitted when rejection was expected
    util.go:670: forbidden error expected, got %!s(<nil>)
        --- FAIL: TestCreateClusterRequestServingIsolation/Main/EnsurePSANotPrivileged (0.16s)
}
```

2024-10-04 11:23 UTC, rtheis commented
/test verify

2024-10-04 18:58 UTC, rtheis requested changes

2024-10-04 18:58 UTC, rtheis commented on test/e2e/create_cluster_test.go
> -		e2eutil.EnsurePSANotPrivileged(t, ctx, guestClient)
Per our slack discussion, I think you need to first remove the test in a separate PR in order for PR testing to pass on this PR.

2024-10-08 10:32 UTC, rtheis commented on test/e2e/create_cluster_test.go
> -		e2eutil.EnsurePSANotPrivileged(t, ctx, guestClient)
https://github.com/openshift/hypershift/pull/4855 will hopefully resolve this.

2024-10-10 16:47 UTC, rtheis commented
/retest-required

2024-10-10 16:47 UTC, rtheis commented
Retesting now that https://github.com/openshift/hypershift/pull/4875 merged.

2024-10-10 19:44 UTC, rtheis commented
/retest-required

2024-10-11 15:26 UTC, rtheis requested changes
Evan please open a Jira for this PR too.

2024-10-11 15:26 UTC, rtheis commented on control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/config.go
> +	if featureGates != nil {
I don't think this is needed.  Similar to `cipherSuites` input, can't we simply set the value to what was passed into this function?

2024-10-14 18:39 UTC, rtheis commented
/retest-required

2024-10-14 19:01 UTC, rtheis commented
/retitle OCPBUGS-43316: Enforce privileged PSA by default

2024-10-14 19:06 UTC, rtheis approved these changes
/lgtm

2024-10-14 19:09 UTC, rtheis commented
@Evan-Reilly I think we may need some Jira magic done to make the tooling happy with this 4.17 only change.  We'll probably need Red Hat help to do this properly.

2024-10-14 19:42 UTC, rtheis commented
/retest-required

2024-10-15 01:06 UTC, rtheis commented
/retest-required

2024-10-15 10:28 UTC, rtheis commented
/retest-required

2024-10-15 10:29 UTC, rtheis commented
@Evan-Reilly if my latest test retry fails, please contact the HyperShift folks for assistance.  There may be a known issue with this test.

2024-10-16 10:15 UTC, rtheis commented
/retest-required

2024-10-16 11:28 UTC, rtheis commented
/jira refresh

2024-10-16 13:38 UTC, rvanderp3 commented
/jira refresh

2024-10-16 13:40 UTC, rvanderp3 commented
/jira refresh

2024-10-16 13:41 UTC, rvanderp3 commented
/jira refresh

2024-10-16 13:45 UTC, sjenning commented
/approve

2024-10-16 13:47 UTC, sjenning commented
/hold

on review from hyperhift team.  didn't really no one from our side had looked yet.

2024-10-16 14:41 UTC, Evan-Reilly commented on control-plane-operator/controllers/hostedcontrolplane/clusterpolicy/params.go
> +func (p *ClusterPolicyControllerParams) FeatureGates() []string {
Yes, just pushed separate PR for that here: https://github.com/openshift/hypershift/pull/4925

2024-10-16 15:19 UTC, sjenning commented
/lgtm
/hold cancel

2024-10-16 22:29 UTC, merged