OCPBUGS-45265: Use /livez/ping endpoint rather than /version
openshift/hypershift pull request #5211
Opened 2024-12-02 15:13 UTC by jonesbr17

**What this PR does / why we need it**: /livez/ping is faster and more reliable than /version. We should prefer /livez/ping when possible.

**Which issue(s) this PR fixes** *(optional, use `fixes #<issue_number>(, fixes #<issue_number>, ...)` format, where issue_number might be a GitHub issue, or a Jira story*:
Fixes #https://issues.redhat.com/browse/OCPBUGS-45265

**Checklist**
- [x] Subject and description added to both, commit and PR.
- [x] Relevant issues have been referenced.
- [ ] This change includes docs. 
- [ ] This change includes unit tests.

2024-12-02 15:58 UTC, rtheis requested changes

2024-12-02 15:58 UTC, rtheis commented on hypershift-operator/controllers/nodepool/apiserver-haproxy/haproxy.cfg
> +  option httpchk GET /livez/ping
We cannot simply switch to `/livez/ping` because it isn't enabled for unauthenticated users by default.

2024-12-03 13:20 UTC, jonesbr17 commented
/retest

2024-12-03 18:32 UTC, rtheis commented on hypershift-operator/controllers/nodepool/haproxy.go
> +func generateNodePublicInfoViewerCR() func() ([]byte, error) {
I don't know if this is the correct location to do this.  This RBAC is cluster scope and not nodepool scoped.  I suspect it belongs in the HCCO along side reconciling the in cluster Kubernetes API server endpoint.  Please ask Red Hat for their opinion.

2024-12-04 11:16 UTC, rtheis commented
@jonesbr17 please also fix the Jira.

2024-12-04 13:52 UTC, jonesbr17 commented
/jira refresh

2025-01-06 01:32 UTC, rtheis commented on hypershift-operator/controllers/nodepool/haproxy.go
> +func generateNodePublicInfoViewerCR() func() ([]byte, error) {
@jonesbr17 any updates on this?

2025-01-09 16:09 UTC, sjenning commented
/retest
/approve

2025-01-09 16:15 UTC, sjenning commented on hypershift-operator/controllers/nodepool/haproxy.go
> +func generateNodePublicInfoViewerCR() func() ([]byte, error) {
Yes, this is true.  HCCO should reconcile this.  Good catch @rtheis :+1:

2025-01-09 16:24 UTC, sjenning commented
/hold
Until the CR/CRB reconcile is moved to the HCCO.  I doubt that this works at all in its current state.

2025-01-10 17:51 UTC, rtheis commented
/retest-required

2025-01-10 22:59 UTC, rtheis commented
/test okd-scos-e2e-aws-ovn

2025-01-10 23:00 UTC, rtheis commented
/remove-hold 

CR/CRB reconcile has been moved to the HCCO.

2025-01-10 23:05 UTC, merged

2025-01-10 23:22 UTC, rtheis commented
/cherry-pick release-4.18

2025-01-13 12:44 UTC, rtheis commented
@jonesbr17 https://github.com/openshift/hypershift/pull/5211#issuecomment-2584791238 ptal

2025-01-13 13:59 UTC, xueqzhan commented
/payload-job periodic-ci-openshift-hypershift-release-4.19-periodics-e2e-aws-ovn-conformance