hypershift creds mount optional
openshift/hypershift pull request #716
Opened 2021-11-26 06:37 UTC by SANJEEV-Choubey

Remove mount and secret from hypershift deployment, when not provided.
https://github.com/openshift/hypershift/issues/651

2021-11-26 06:42 UTC, hasan4791 commented
/ok-to-test

2021-11-29 05:03 UTC, relyt0925 commented
@SANJEEV-Choubey Could we also disable the deployment of the following secrets when not necessary
```
+  - apiVersion: v1
+    data:
+      credentials: null
+    kind: Secret
+    metadata:
+      creationTimestamp: null
+      name: hypershift-operator-aws-credentials
+      namespace: hypershift
+  - apiVersion: v1
+    data:
+      credentials: null
+    kind: Secret
+    metadata:
+      creationTimestamp: null
+      name: hypershift-operator-oidc-provider-s3-credentials
+      namespace: hypershift
+  - apiVersion: v1
+    data:
+      name: ""
+      region: ""
+    kind: ConfigMap
+    metadata:
+      creationTimestamp: null
+      name: oidc-storage-provider-s3-config
+      namespace: kube-public
```

2021-11-29 10:06 UTC, SANJEEV-Choubey commented
/test e2e-aws-pooled

2021-11-29 10:23 UTC, SANJEEV-Choubey commented
/retest

2021-12-01 04:06 UTC, SANJEEV-Choubey commented
/test e2e-aws

2021-12-01 15:35 UTC, SANJEEV-Choubey commented
/test ?

2021-12-02 05:31 UTC, SANJEEV-Choubey commented
/retest-required

2021-12-02 14:09 UTC, SANJEEV-Choubey commented
/assign @ironcladlou

2021-12-02 15:10 UTC, sjenning requested changes

2021-12-02 15:10 UTC, sjenning commented on cmd/install/install.go
> +		objects = append(objects, operatorCredentialsSecret)
This secret is related to private cluster operations on AWS, not OIDC storage.  Thus it should not be tied into the bucket name being specified.

2021-12-03 05:53 UTC, SANJEEV-Choubey commented
/retest-required

2021-12-03 16:16 UTC, sjenning commented
/lgtm
/approve

2021-12-03 17:24 UTC, merged