Refactor context usage in the CLI, to reduce code duplication
openshift/hypershift pull request #883
Opened 2022-01-20 07:45 UTC by nunnatsa

Refactor the CLI to use the same context. Replace the `Run` function by `RunE` to return errors from the cmd implementation, instead of `exit(1)` from unexpected locations, the command abortion will be done from one place at the root command.

Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

2022-01-20 15:33 UTC, ironcladlou requested changes

2022-01-20 16:12 UTC, nunnatsa commented on main.go
> +		os.Exit(1)
Makes sense to add it. But I don't think we need to remove `os.Exit()`

2022-01-20 16:16 UTC, ironcladlou commented on main.go
> +		os.Exit(1)
I don't understand. Adding `os.Exit()` here will cause the process to exit, not giving the code a chance to gracefully terminate in response to the context closure, which defeats the entire purpose. The intent of the SIGINT handler is to trigger a graceful shutdown via context closure. Calling `os.Exit()` in this context seems incorrect and a regression.

2022-01-20 16:21 UTC, nunnatsa commented on main.go
> +		os.Exit(1)
@ironcladlou - `cancel()` added

2022-01-21 19:09 UTC, nunnatsa commented
/retest

2022-01-25 15:30 UTC, ironcladlou commented on main.go
> +
Just noticed these package variables, looks like they aren't referenced anywhere?

2022-01-26 08:39 UTC, nunnatsa commented on main.go
> +
removed

2022-01-26 14:40 UTC, ironcladlou commented
Thanks, I think it's all looking correct now.

/lgtm
/approve

2022-01-26 14:42 UTC, merged